#define CRITICAL_PERCENTAGE 0.15
#define EXECUTABLE_NAME "rossa"
#define LOW_PERCENTAGE 0.25
#define MINIMUM_CHARGE 0.06
#define NAG_WHEN_ENOUGH false
#define OUGHT_TO_BE_ENOUGH 0.98
#define SLEEP_PERIOD 60
